name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      
      CI: true
    strategy:
      fail-fast: false
      matrix:
        
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    
    - name: Run tests
      run: |
        bundle exec rake test
    

